version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: bpr
    main: ./cmd/bpr
    binary: bpr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/victorhsb/branchless-pr/internal/cli.version={{.Version}}

checksum:
  name_template: checksums.txt

archives:
  - id: bpr
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

changelog:
  use: github-native

# Cosign keyless signing (Github OIDC)
signs:
  - cmd: cosign
    env:
      - COSIGN_YES=true
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all

snapshot:
  version_template: "{{.Version}}-next"
